// <auto-generated />
using ApiLivrosMeusDados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLivrosMeusDados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("ApiLivrosMeusDados.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autores")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2019,
                            Autores = "LEDUR, Cleverson Lopes",
                            Cidade = "Porto Alegre",
                            Editora = "SAGAH",
                            Titulo = "Programação Back End II"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2021,
                            Autores = "FREITAS, Pedro H. Chagas [et al.]",
                            Cidade = "Porto Alegre",
                            Editora = "SAGAH",
                            Titulo = "Programação Back End III"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2008,
                            Autores = "DEITEL, Paul J.",
                            Cidade = "São Paulo",
                            Editora = "Pearson Prentice Hall",
                            Titulo = "Ajax, RICH Internet Applications e desenvolvimento Web para programadores"
                        });
                });

            modelBuilder.Entity("ApiLivrosMeusDados.Models.MeusDados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeusDados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Curso = "Analise e Desenvolvimento de Sistemas",
                            Nome = "Roger de Oliveira Lima",
                            RU = "3842061"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
